package com.epn.moodle.entidades;

// Generated 16/07/2015 13:52:11 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Asignatura generated by hbm2java
 */
@Entity
@Table(name = "asignatura", schema = "public")
@NamedQuery(name = "Asignatura.findAll",query="SELECT a FROM Asignatura a")
public class Asignatura implements java.io.Serializable {

	private int idAsignatura;
	private String nombreAsignatura;
	private String descripcionAsignatura;
	private BigDecimal calificacionUnoAsignatura;
	private BigDecimal calificacionDosAsignatura;
	private BigDecimal calificacionTresAsignatura;
	private Set<Periodo> periodos = new HashSet<Periodo>(0);
	private Set<Actividad> actividads = new HashSet<Actividad>(0);

	public Asignatura() {
	}

	public Asignatura(int idAsignatura, String nombreAsignatura,
			String descripcionAsignatura, BigDecimal calificacionUnoAsignatura,
			BigDecimal calificacionDosAsignatura) {
		this.idAsignatura = idAsignatura;
		this.nombreAsignatura = nombreAsignatura;
		this.descripcionAsignatura = descripcionAsignatura;
		this.calificacionUnoAsignatura = calificacionUnoAsignatura;
		this.calificacionDosAsignatura = calificacionDosAsignatura;
	}

	public Asignatura(int idAsignatura, String nombreAsignatura,
			String descripcionAsignatura, BigDecimal calificacionUnoAsignatura,
			BigDecimal calificacionDosAsignatura,
			BigDecimal calificacionTresAsignatura, Set<Periodo> periodos,
			Set<Actividad> actividads) {
		this.idAsignatura = idAsignatura;
		this.nombreAsignatura = nombreAsignatura;
		this.descripcionAsignatura = descripcionAsignatura;
		this.calificacionUnoAsignatura = calificacionUnoAsignatura;
		this.calificacionDosAsignatura = calificacionDosAsignatura;
		this.calificacionTresAsignatura = calificacionTresAsignatura;
		this.periodos = periodos;
		this.actividads = actividads;
	}

	@Id
	@Column(name = "id_asignatura", unique = true, nullable = false)
	public int getIdAsignatura() {
		return this.idAsignatura;
	}

	public void setIdAsignatura(int idAsignatura) {
		this.idAsignatura = idAsignatura;
	}

	@Column(name = "nombre_asignatura", nullable = false, length = 50)
	public String getNombreAsignatura() {
		return this.nombreAsignatura;
	}

	public void setNombreAsignatura(String nombreAsignatura) {
		this.nombreAsignatura = nombreAsignatura;
	}

	@Column(name = "descripcion_asignatura", nullable = false, length = 150)
	public String getDescripcionAsignatura() {
		return this.descripcionAsignatura;
	}

	public void setDescripcionAsignatura(String descripcionAsignatura) {
		this.descripcionAsignatura = descripcionAsignatura;
	}

	@Column(name = "calificacion_uno_asignatura", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getCalificacionUnoAsignatura() {
		return this.calificacionUnoAsignatura;
	}

	public void setCalificacionUnoAsignatura(
			BigDecimal calificacionUnoAsignatura) {
		this.calificacionUnoAsignatura = calificacionUnoAsignatura;
	}

	@Column(name = "calificacion_dos_asignatura", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getCalificacionDosAsignatura() {
		return this.calificacionDosAsignatura;
	}

	public void setCalificacionDosAsignatura(
			BigDecimal calificacionDosAsignatura) {
		this.calificacionDosAsignatura = calificacionDosAsignatura;
	}

	@Column(name = "calificacion_tres_asignatura", precision = 131089, scale = 0)
	public BigDecimal getCalificacionTresAsignatura() {
		return this.calificacionTresAsignatura;
	}

	public void setCalificacionTresAsignatura(
			BigDecimal calificacionTresAsignatura) {
		this.calificacionTresAsignatura = calificacionTresAsignatura;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "asignatura")
	public Set<Periodo> getPeriodos() {
		return this.periodos;
	}

	public void setPeriodos(Set<Periodo> periodos) {
		this.periodos = periodos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "asignatura")
	public Set<Actividad> getActividads() {
		return this.actividads;
	}

	public void setActividads(Set<Actividad> actividads) {
		this.actividads = actividads;
	}

}
