package com.epn.moodle.entidades;

// Generated 16/07/2015 13:52:11 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Periodo generated by hbm2java
 */
@Entity
@Table(name = "periodo", schema = "public")
public class Periodo implements java.io.Serializable {

	private int idPeriodo;
	private Asignatura asignatura;
	private Persona persona;
	private String nombrePeriodo;
	private Date fechaInicioPeriodo;
	private Date fechaFinPeriodo;

	public Periodo() {
	}

	public Periodo(int idPeriodo, String nombrePeriodo,
			Date fechaInicioPeriodo, Date fechaFinPeriodo) {
		this.idPeriodo = idPeriodo;
		this.nombrePeriodo = nombrePeriodo;
		this.fechaInicioPeriodo = fechaInicioPeriodo;
		this.fechaFinPeriodo = fechaFinPeriodo;
	}

	public Periodo(int idPeriodo, Asignatura asignatura, Persona persona,
			String nombrePeriodo, Date fechaInicioPeriodo, Date fechaFinPeriodo) {
		this.idPeriodo = idPeriodo;
		this.asignatura = asignatura;
		this.persona = persona;
		this.nombrePeriodo = nombrePeriodo;
		this.fechaInicioPeriodo = fechaInicioPeriodo;
		this.fechaFinPeriodo = fechaFinPeriodo;
	}

	@Id
	@Column(name = "id_periodo", unique = true, nullable = false)
	public int getIdPeriodo() {
		return this.idPeriodo;
	}

	public void setIdPeriodo(int idPeriodo) {
		this.idPeriodo = idPeriodo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_asignatura")
	public Asignatura getAsignatura() {
		return this.asignatura;
	}

	public void setAsignatura(Asignatura asignatura) {
		this.asignatura = asignatura;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona")
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Column(name = "nombre_periodo", nullable = false, length = 30)
	public String getNombrePeriodo() {
		return this.nombrePeriodo;
	}

	public void setNombrePeriodo(String nombrePeriodo) {
		this.nombrePeriodo = nombrePeriodo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_inicio_periodo", nullable = false, length = 13)
	public Date getFechaInicioPeriodo() {
		return this.fechaInicioPeriodo;
	}

	public void setFechaInicioPeriodo(Date fechaInicioPeriodo) {
		this.fechaInicioPeriodo = fechaInicioPeriodo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_fin_periodo", nullable = false, length = 13)
	public Date getFechaFinPeriodo() {
		return this.fechaFinPeriodo;
	}

	public void setFechaFinPeriodo(Date fechaFinPeriodo) {
		this.fechaFinPeriodo = fechaFinPeriodo;
	}

}
