package com.epn.moodle.entidades;

// Generated 16/07/2015 13:52:11 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Persona generated by hbm2java
 */
@Entity
@Table(name = "persona", schema = "public")
public class Persona implements java.io.Serializable {

	private int idPersona;
	private String nombrePersona;
	private String apellidosPersona;
	private String cedulaPersona;
	private Set<Periodo> periodos = new HashSet<Periodo>(0);

	public Persona() {
	}

	public Persona(int idPersona, String nombrePersona,
			String apellidosPersona, String cedulaPersona) {
		this.idPersona = idPersona;
		this.nombrePersona = nombrePersona;
		this.apellidosPersona = apellidosPersona;
		this.cedulaPersona = cedulaPersona;
	}

	public Persona(int idPersona, String nombrePersona,
			String apellidosPersona, String cedulaPersona, Set<Periodo> periodos) {
		this.idPersona = idPersona;
		this.nombrePersona = nombrePersona;
		this.apellidosPersona = apellidosPersona;
		this.cedulaPersona = cedulaPersona;
		this.periodos = periodos;
	}

	@Id
	@Column(name = "id_persona", unique = true, nullable = false)
	public int getIdPersona() {
		return this.idPersona;
	}

	public void setIdPersona(int idPersona) {
		this.idPersona = idPersona;
	}

	@Column(name = "nombre_persona", nullable = false, length = 50)
	public String getNombrePersona() {
		return this.nombrePersona;
	}

	public void setNombrePersona(String nombrePersona) {
		this.nombrePersona = nombrePersona;
	}

	@Column(name = "apellidos_persona", nullable = false, length = 50)
	public String getApellidosPersona() {
		return this.apellidosPersona;
	}

	public void setApellidosPersona(String apellidosPersona) {
		this.apellidosPersona = apellidosPersona;
	}

	@Column(name = "cedula_persona", nullable = false, length = 15)
	public String getCedulaPersona() {
		return this.cedulaPersona;
	}

	public void setCedulaPersona(String cedulaPersona) {
		this.cedulaPersona = cedulaPersona;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persona")
	public Set<Periodo> getPeriodos() {
		return this.periodos;
	}

	public void setPeriodos(Set<Periodo> periodos) {
		this.periodos = periodos;
	}

}
