package com.epn.saew.entidades;

// Generated 16/07/2015 13:40:32 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Periodo generated by hbm2java
 */
@Entity
@Table(name = "periodo", schema = "public")
public class Periodo implements java.io.Serializable {

	private int idPeriodo;
	private Date fechaInicioPeriodo;
	private Date fechaFinPeriodo;
	private String nombrePeriodo;
	private BigDecimal calificacionUno;
	private BigDecimal calificacionDos;
	private BigDecimal calificacionTres;
	private Set<Asignatura> asignaturas = new HashSet<Asignatura>(0);
	private Set<Persona> personas = new HashSet<Persona>(0);

	public Periodo() {
	}

	public Periodo(int idPeriodo, Date fechaInicioPeriodo,
			Date fechaFinPeriodo, String nombrePeriodo,
			BigDecimal calificacionUno, BigDecimal calificacionDos) {
		this.idPeriodo = idPeriodo;
		this.fechaInicioPeriodo = fechaInicioPeriodo;
		this.fechaFinPeriodo = fechaFinPeriodo;
		this.nombrePeriodo = nombrePeriodo;
		this.calificacionUno = calificacionUno;
		this.calificacionDos = calificacionDos;
	}

	public Periodo(int idPeriodo, Date fechaInicioPeriodo,
			Date fechaFinPeriodo, String nombrePeriodo,
			BigDecimal calificacionUno, BigDecimal calificacionDos,
			BigDecimal calificacionTres, Set<Asignatura> asignaturas,
			Set<Persona> personas) {
		this.idPeriodo = idPeriodo;
		this.fechaInicioPeriodo = fechaInicioPeriodo;
		this.fechaFinPeriodo = fechaFinPeriodo;
		this.nombrePeriodo = nombrePeriodo;
		this.calificacionUno = calificacionUno;
		this.calificacionDos = calificacionDos;
		this.calificacionTres = calificacionTres;
		this.asignaturas = asignaturas;
		this.personas = personas;
	}

	@Id
	@Column(name = "id_periodo", unique = true, nullable = false)
	public int getIdPeriodo() {
		return this.idPeriodo;
	}

	public void setIdPeriodo(int idPeriodo) {
		this.idPeriodo = idPeriodo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_inicio_periodo", nullable = false, length = 13)
	public Date getFechaInicioPeriodo() {
		return this.fechaInicioPeriodo;
	}

	public void setFechaInicioPeriodo(Date fechaInicioPeriodo) {
		this.fechaInicioPeriodo = fechaInicioPeriodo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_fin_periodo", nullable = false, length = 13)
	public Date getFechaFinPeriodo() {
		return this.fechaFinPeriodo;
	}

	public void setFechaFinPeriodo(Date fechaFinPeriodo) {
		this.fechaFinPeriodo = fechaFinPeriodo;
	}

	@Column(name = "nombre_periodo", nullable = false, length = 15)
	public String getNombrePeriodo() {
		return this.nombrePeriodo;
	}

	public void setNombrePeriodo(String nombrePeriodo) {
		this.nombrePeriodo = nombrePeriodo;
	}

	@Column(name = "calificacion_uno", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getCalificacionUno() {
		return this.calificacionUno;
	}

	public void setCalificacionUno(BigDecimal calificacionUno) {
		this.calificacionUno = calificacionUno;
	}

	@Column(name = "calificacion_dos", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getCalificacionDos() {
		return this.calificacionDos;
	}

	public void setCalificacionDos(BigDecimal calificacionDos) {
		this.calificacionDos = calificacionDos;
	}

	@Column(name = "calificacion_tres", precision = 131089, scale = 0)
	public BigDecimal getCalificacionTres() {
		return this.calificacionTres;
	}

	public void setCalificacionTres(BigDecimal calificacionTres) {
		this.calificacionTres = calificacionTres;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "periodo")
	public Set<Asignatura> getAsignaturas() {
		return this.asignaturas;
	}

	public void setAsignaturas(Set<Asignatura> asignaturas) {
		this.asignaturas = asignaturas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "periodo")
	public Set<Persona> getPersonas() {
		return this.personas;
	}

	public void setPersonas(Set<Persona> personas) {
		this.personas = personas;
	}

}
