package com.epn.saew.entidades;

// Generated 16/07/2015 13:40:32 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Asignatura generated by hbm2java
 */
@Entity
@Table(name = "asignatura", schema = "public")
@NamedQuery(name = "Asignatura.findAll",query="SELECT a FROM Asignatura a")
public class Asignatura implements java.io.Serializable {

	private int idAsignatura;
	private Periodo periodo;
	private String nombreAsignatura;
	private int numeroCreditosAsignatura;

	public Asignatura() {
	}

	public Asignatura(int idAsignatura, String nombreAsignatura,
			int numeroCreditosAsignatura) {
		this.idAsignatura = idAsignatura;
		this.nombreAsignatura = nombreAsignatura;
		this.numeroCreditosAsignatura = numeroCreditosAsignatura;
	}

	public Asignatura(int idAsignatura, Periodo periodo,
			String nombreAsignatura, int numeroCreditosAsignatura) {
		this.idAsignatura = idAsignatura;
		this.periodo = periodo;
		this.nombreAsignatura = nombreAsignatura;
		this.numeroCreditosAsignatura = numeroCreditosAsignatura;
	}

	@Id
	@Column(name = "id_asignatura", unique = true, nullable = false)
	public int getIdAsignatura() {
		return this.idAsignatura;
	}

	public void setIdAsignatura(int idAsignatura) {
		this.idAsignatura = idAsignatura;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_periodo")
	public Periodo getPeriodo() {
		return this.periodo;
	}

	public void setPeriodo(Periodo periodo) {
		this.periodo = periodo;
	}

	@Column(name = "nombre_asignatura", nullable = false, length = 75)
	public String getNombreAsignatura() {
		return this.nombreAsignatura;
	}

	public void setNombreAsignatura(String nombreAsignatura) {
		this.nombreAsignatura = nombreAsignatura;
	}

	@Column(name = "numero_creditos_asignatura", nullable = false)
	public int getNumeroCreditosAsignatura() {
		return this.numeroCreditosAsignatura;
	}

	public void setNumeroCreditosAsignatura(int numeroCreditosAsignatura) {
		this.numeroCreditosAsignatura = numeroCreditosAsignatura;
	}

}
