package com.epn.saew.entidades;

// Generated 16/07/2015 13:40:32 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Persona generated by hbm2java
 */
@Entity
@Table(name = "persona", schema = "public")
@NamedQuery(name = "Persona.findAll",query="SELECT p FROM Persona p")
public class Persona implements java.io.Serializable {

	private int idPersona;
	private Rol rol;
	private Periodo periodo;
	private String nombrePersona;
	private String apellidosPersona;
	private String cedulaPersona;
	private String numeroUnico;

	public Persona() {
	}

	public Persona(int idPersona, String nombrePersona,
			String apellidosPersona, String cedulaPersona) {
		this.idPersona = idPersona;
		this.nombrePersona = nombrePersona;
		this.apellidosPersona = apellidosPersona;
		this.cedulaPersona = cedulaPersona;
	}

	public Persona(int idPersona, Rol rol, Periodo periodo,
			String nombrePersona, String apellidosPersona,
			String cedulaPersona, String numeroUnico) {
		this.idPersona = idPersona;
		this.rol = rol;
		this.periodo = periodo;
		this.nombrePersona = nombrePersona;
		this.apellidosPersona = apellidosPersona;
		this.cedulaPersona = cedulaPersona;
		this.numeroUnico = numeroUnico;
	}

	@Id
	@Column(name = "id_persona", unique = true, nullable = false)
	public int getIdPersona() {
		return this.idPersona;
	}

	public void setIdPersona(int idPersona) {
		this.idPersona = idPersona;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_rol")
	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_periodo")
	public Periodo getPeriodo() {
		return this.periodo;
	}

	public void setPeriodo(Periodo periodo) {
		this.periodo = periodo;
	}

	@Column(name = "nombre_persona", nullable = false, length = 50)
	public String getNombrePersona() {
		return this.nombrePersona;
	}

	public void setNombrePersona(String nombrePersona) {
		this.nombrePersona = nombrePersona;
	}

	@Column(name = "apellidos_persona", nullable = false, length = 50)
	public String getApellidosPersona() {
		return this.apellidosPersona;
	}

	public void setApellidosPersona(String apellidosPersona) {
		this.apellidosPersona = apellidosPersona;
	}

	@Column(name = "cedula_persona", nullable = false, length = 13)
	public String getCedulaPersona() {
		return this.cedulaPersona;
	}

	public void setCedulaPersona(String cedulaPersona) {
		this.cedulaPersona = cedulaPersona;
	}

	@Column(name = "numero_unico", length = 15)
	public String getNumeroUnico() {
		return this.numeroUnico;
	}

	public void setNumeroUnico(String numeroUnico) {
		this.numeroUnico = numeroUnico;
	}

}
