package com.epn.saew.entidades;

// Generated 16/07/2015 13:40:32 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(name = "rol", schema = "public")
@NamedQuery(name = "Rol.findAll",query="SELECT r FROM Rol r")
public class Rol implements java.io.Serializable {

	private int idRol;
	private String nombreRol;
	private Set<Persona> personas = new HashSet<Persona>(0);

	public Rol() {
	}

	public Rol(int idRol, String nombreRol) {
		this.idRol = idRol;
		this.nombreRol = nombreRol;
	}

	public Rol(int idRol, String nombreRol, Set<Persona> personas) {
		this.idRol = idRol;
		this.nombreRol = nombreRol;
		this.personas = personas;
	}

	@Id
	@Column(name = "id_rol", unique = true, nullable = false)
	public int getIdRol() {
		return this.idRol;
	}

	public void setIdRol(int idRol) {
		this.idRol = idRol;
	}

	@Column(name = "nombre_rol", nullable = false, length = 50)
	public String getNombreRol() {
		return this.nombreRol;
	}

	public void setNombreRol(String nombreRol) {
		this.nombreRol = nombreRol;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rol")
	public Set<Persona> getPersonas() {
		return this.personas;
	}

	public void setPersonas(Set<Persona> personas) {
		this.personas = personas;
	}

}
